import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const { user, isLoaded, isSignedIn } = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className=" bg-slate-200">
          <p>User?.username: {JSON.stringify(user?.emailAddresses)}</p>
          <p>isLoaded: {String(isLoaded)}</p>
          <p>isSignedIn: {String(isSignedIn)}</p>
          {user !== null && user !== undefined ? (
            <SignOutButton />
          ) : (
            <SignInButton />
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
